<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VSModifier.Core\VSModifier.Core.csproj" />
    <ProjectReference Include="..\VSModifier.Memory\VSModifier.Memory.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\data\offsets.json"
          Link="data\offsets.json"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\data\ids\unlocks.json"
          Link="data\ids\unlocks.json"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\data\ids\forced-level-up-items.json"
          Link="data\ids\forced-level-up-items.json"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\README.md"
          Link="README.md"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
    <None Include="..\LICENSE"
          Link="LICENSE"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
